name: CI Actions
on: [push]
jobs:
  export-requirements:
    name: "Export requirements.txt"
    # skip this job when already in a -fixup branch
    if: "!endsWith(github.head_ref, '-fixup')"
    runs-on: ubuntu-latest
    permissions:
      # this job needs permissions to push new commits and create/modify
      # pull requests
      contents: write
      pull-requests: write
    container:
      image: vertigo1/magicpr-demo:latest
    steps:
      - uses: actions/checkout@v2
      - name: install poetry and re-export requirements.txt
        run: |
          apt-get update
          apt-get install -y python3 python3-pip
          pip3 install poetry
          poetry export -f requirements.txt -o requirements.txt
          poetry export -f requirements.txt -o requirements_dev.txt --dev
      - name: push any changes as a new PR
        run: |
          magicpr suggest-changes \
            --auth-token="${{ github.token }}" \
            --commit-author="${{ github.event.commits[0].author.name }}" \
            --commit-email="${{ github.event.commits[0].author.email }}" \
            --branch-suffix=-fixup \
            --commit-message='Re-exported requirements.txt and/or requirements_dev.txt' \
            --guidance='Please merge requirements.txt and/or requirements_dev.txt which have been exported from the latest poetry.lock'

  linters:
    runs-on: ubuntu-latest
    steps:
      - name: install python3
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: install deps
        run: pip3.9 install -r requirements.txt -r requirements_dev.txt
      - name: flake8
        run: flake8 python_ansible_wrapper
      - name: mypy
        run: mypy .
