name: CI Actions
on: [push]
jobs:
  linters:
    runs-on: ubuntu-latest
    steps:
      - name: install python3
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: install deps
        run: pip3.9 install -r requirements.txt -r requirements_dev.txt
      - name: flake8
        run: flake8 python_ansible_wrapper
      - name: mypy
        run: mypy .
